apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secrets
  namespace: default
spec:
  encryptedData:
    password: AgCCZbmsWvhOPR5VOTsbjirkVf9NglFTuud5sytilym90Td8XCaulJZQ292iYx7a8y/u6tV+D2Jv8fOSIA0TwD1iMao/UV1HJ+cir4o07QUSws3hfcg8H3epiWEUU2nH/j1rlZY7POhVRlnVOHcaY5DHCkXEzl3MTvFqM0HeaqzipeorPKiWqxDro6/ruU38DRchJTa3nLXhJ62S53TJHKk7qKpmVThf11fSzPv82bA8UthI1bcoAtEDCKCpsmJCVfYtnhDVcsjQhLXQ9JZ5ltum4XaSXWZ88qS/h/X2p6Xsg+ugP79oqJbMexk7yl1S7ay8G2eIuTYBIhbKIJjPkEAG/5dUUqzr7c+eKA9BRsqB51rSamNCcAOGOD3aPUZnbqop6TmMjf8kSzIuMX1omp/LAu5NxH/d7hrofmr1QsSt0QtPf8Pauc31ktYFfPtMZDnR6mG501nednojobU9ziWOCR6y/OPhmwlOc8Fje48nzsJ8EtUQa5lZcxxqL9zFavZuuIZyTDDy/K6ww3A9FVF/u/cBSdNalzgT8irte6EaXrwURvpPhirfq6QtyLwLVGzJUorzdExtyX1IRYkQFFcgsguzDfLB3rlaRXYEkwO/RievWrVBQLfReAXTu+ofnX8vHkM2LM2vvzbyGXJoiCUTjtsP4yT5ySOMm0GrSY8CtAGQb83IOLHwV1IP8O7/QIe7zK8FVJqYpQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-secrets
      namespace: default
    type: Opaque

